"""empty message

Revision ID: 460d96ac90e5
Revises: 92b96bfd1446
Create Date: 2020-09-24 15:26:34.571603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d96ac90e5'
down_revision = '92b96bfd1446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('question_category_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    op.drop_column('question', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_category_fkey', 'question', 'category', ['category'], ['id'])
    op.drop_column('question', 'category_id')
    # ### end Alembic commands ###
